/*************************************************************************
 * SINGLE-FILE NODE.JS APPLICATION (ES5, CommonJS, NO backticks)
 *
 * Features:
 *  - 4 Fonts: Montserrat, Playfair Display, Lora, Spectral
 *  - Italic placeholders using Spectral with smaller font size
 *  - Header with "3D effect" & heavier boldness
 *  - Recolored progress bar
 *  - Steps: Basic Info (large artist list), Address (50 states), Signature, Camera
 *  - Client-side PDF generation (jsPDF)
 *************************************************************************/

var express = require('express');
var app = express();

// Dynamically set the port using environment variable or default to 3000
var PORT = process.env.PORT || 3000;

// Serve the main page
app.get('/', function(req, res) {

  // Entire HTML Content as a string
  var htmlContent = ""
+ "<!DOCTYPE html>\n"
+ "<html lang=\"en\">\n"
+ "<head>\n"
+ "  <meta charset=\"UTF-8\">\n"
+ "  <title>Meet With Artist Application</title>\n"
+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
+ "\n"
// 4 Fonts
+ "  <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Playfair+Display:wght@700;900&family=Lora:wght@400;700&family=Spectral:wght@400;700&display=swap\" rel=\"stylesheet\">\n"
+ "\n"
// jsPDF from CDN
+ "  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js\"></script>\n"
+ "\n"
// Inline CSS
+ "  <style>\n"
+ "    /* Root & Body */\n"
+ "    body {\n"
+ "      margin:0; padding:0;\n"
+ "      font-family:'Montserrat', sans-serif;\n"
+ "      background: linear-gradient(135deg, #f5f5f5 0%, #e5e5e5 100%);\n"
+ "      color:#333;\n"
+ "    }\n"
+ "\n"
+ "    .container {\n"
+ "      max-width:800px; margin:2rem auto; padding:0 1rem;\n"
+ "    }\n"
+ "\n"
+ "    /* HEADER */\n"
+ "    .header {\n"
+ "      background:#1a1a1a; color:#fff;\n"
+ "      padding:2rem; border-radius:8px;\n"
+ "      margin-bottom:2rem; position:relative;\n"
+ "      box-shadow:0 4px 6px rgba(0,0,0,0.1);\n"
+ "    }\n"
+ "    .logo-area {\n"
+ "      text-align:center; margin-bottom:1rem;\n"
+ "    }\n"
+ "    .logo-area img {\n"
+ "      max-width:220px; height:auto;\n"
+ "    }\n"
+ "\n"
+ "    .header h1 {\n"
+ "      font-family:'Playfair Display', serif;\n"
+ "      font-weight:900; /* heavier boldness */\n"
+ "      font-size:1.8rem;\n"
+ "      text-align:center;\n"
+ "      margin-top:1rem;\n"
+ "      text-transform:uppercase;\n"
+ "      letter-spacing:1px;\n"
+ "      /* 3D effect with heavier shadow */\n"
+ "      text-shadow:3px 3px 5px rgba(0,0,0,0.5);\n"
+ "      background: linear-gradient(-45deg, #ffd700, #c41230);\n"
+ "      background-size:400% 400%;\n"
+ "      -webkit-background-clip:text;\n"
+ "      -webkit-text-fill-color:transparent;\n"
+ "      animation: gradientFlow 5s ease infinite;\n"
+ "    }\n"
+ "    @keyframes gradientFlow {\n"
+ "      0%{ background-position:0% 50%;}\n"
+ "      50%{ background-position:100% 50%;}\n"
+ "      100%{ background-position:0% 50%;}\n"
+ "    }\n"
+ "\n"
+ "    /* Explanation Paragraph */\n"
+ "    .explanation {\n"
+ "      font-family:'Lora', serif;\n"
+ "      font-size:0.95rem;\n"
+ "      margin-bottom:1rem;\n"
+ "      background:rgba(255,255,255,0.8);\n"
+ "      padding:0.75rem; border-radius:6px;\n"
+ "      color:#555;\n"
+ "    }\n"
+ "\n"
+ "    /* PROGRESS BAR */\n"
+ "    .progress-container {\n"
+ "      margin-bottom:2rem;\n"
+ "    }\n"
+ "    .progress {\n"
+ "      height:1.25rem; border-radius:8px;\n"
+ "      overflow:hidden; background-color:#e9ecef;\n"
+ "      box-shadow:0 4px 6px rgba(0,0,0,0.1);\n"
+ "    }\n"
+ "    .progress-bar {\n"
+ "      /* Recolored progress bar gradient */\n"
+ "      background:linear-gradient(45deg, #b22222, #ff4500);\n"
+ "      transition:width 0.5s; position:relative; width:25%;\n"
+ "    }\n"
+ "    .progress-bar span {\n"
+ "      position:absolute; top:0; left:0; width:100%; text-align:center;\n"
+ "      color:#fff; font-weight:600; text-shadow:1px 1px 2px rgba(0,0,0,0.3);\n"
+ "    }\n"
+ "\n"
+ "    .form-section {\n"
+ "      display:none; background:rgba(255,255,255,0.95);\n"
+ "      border-radius:8px; padding:2rem; margin-bottom:2rem;\n"
+ "      box-shadow:0 4px 6px rgba(0,0,0,0.1);\n"
+ "    }\n"
+ "    .form-section.active { display:block;}\n"
+ "    .form-section h2 {\n"
+ "      color:#1a1a1a; margin-bottom:1.5rem; font-size:1.5rem;\n"
+ "      border-bottom:2px solid #c41230; padding-bottom:0.5rem;\n"
+ "      font-family:'Playfair Display', serif;\n"
+ "    }\n"
+ "\n"
+ "    /* LABELS & PLACEHOLDERS (Spectral) */\n"
+ "    .form-label {\n"
+ "      font-family:'Spectral', serif;\n"
+ "      font-size:0.95rem;\n"
+ "      font-style:italic;\n"
+ "      font-weight:bold;\n"
+ "    }\n"
+ "    .form-control, .form-select {\n"
+ "      width:100%; padding:0.5rem; margin-bottom:0.5rem;\n"
+ "      font-family:'Lora', serif; font-size:0.9rem;\n"
+ "    }\n"
+ "    /* Italic placeholders in smaller font using Spectral */\n"
+ "    ::placeholder {\n"
+ "      font-family:'Spectral', serif;\n"
+ "      font-size:0.85rem;\n"
+ "      font-style:italic;\n"
+ "      color:#999;\n"
+ "    }\n"
+ "    .is-invalid { border:2px solid red;}\n"
+ "\n"
+ "    /* SIGNATURE CANVAS */\n"
+ "    #signatureCanvas {\n"
+ "      border:2px dashed #c41230;\n"
+ "      width:100%; height:200px; background:#fff;\n"
+ "      cursor:crosshair; border-radius:8px; touch-action:none;\n"
+ "    }\n"
+ "\n"
+ "    /* CAMERA */\n"
+ "    #videoElement, #capturedImage {\n"
+ "      width:100%; max-height:300px; margin-bottom:1rem;\n"
+ "      border:2px dashed #c41230; border-radius:8px; display:block;\n"
+ "    }\n"
+ "    #capturedImage { display:none; }\n"
+ "\n"
+ "    /* NAV BUTTONS */\n"
+ "    .navigation-buttons {\n"
+ "      display:flex; justify-content:space-between; margin-top:2rem;\n"
+ "    }\n"
+ "    .btn {\n"
+ "      border-radius:8px; padding:0.6rem 1.2rem;\n"
+ "      cursor:pointer; border:none; font-size:1rem;\n"
+ "    }\n"
+ "    .btn-previous {\n"
+ "      background-color:#6c757d; color:#fff;\n"
+ "    }\n"
+ "    .btn-previous:hover {\n"
+ "      background-color:#5a6268;\n"
+ "    }\n"
+ "    .btn-next {\n"
+ "      background-color:#c41230; color:#fff;\n"
+ "    }\n"
+ "    .btn-next:hover {\n"
+ "      background-color:#a61028;\n"
+ "    }\n"
+ "    .btn-camera {\n"
+ "      background-color:#ffd700; color:#333;\n"
+ "    }\n"
+ "    .btn-camera:hover {\n"
+ "      background-color:#f4c700;\n"
+ "    }\n"
+ "    .btn-info {\n"
+ "      background-color:#17a2b8; color:#fff;\n"
+ "    }\n"
+ "    .btn-info:hover {\n"
+ "      background-color:#138496;\n"
+ "    }\n"
+ "\n"
+ "    /* SPINNER & FINAL INSTRUCTIONS */\n"
+ "    .spinner {\n"
+ "      display:none; text-align:center; margin-top:1rem;\n"
+ "    }\n"
+ "    .final-instructions {\n"
+ "      text-align:center; font-weight:bold; color:#c41230;\n"
+ "      font-size:1rem; margin-top:2rem; display:none;\n"
+ "    }\n"
+ "  </style>\n"
+ "</head>\n"
+ "<body>\n"
+ "  <div class=\"container\">\n"
+ "    <div class=\"header\">\n"
+ "      <div class=\"logo-area\">\n"
+ "        <img src=\"https://www.bigmachinelabelgroup.com/files/2022/09/logo-600x82.png\" alt=\"BMLG Logo\">\n"
+ "      </div>\n"
+ "      <h1>Meet With Artist Application</h1>\n"
+ "    </div>\n"
+ "\n"
// Explanation paragraph
+ "    <div class=\"explanation\">\n"
+ "      Please complete all four steps. Fields with <em>italic placeholders</em>\n"
+ "      indicate what to enter. On Step 3, draw your signature. On Step 4, capture\n"
+ "      a photo. Finally, download the completed PDF and email it to \n"
+ "      <strong>pr@bmlgartists.com</strong>.\n"
+ "    </div>\n"
+ "\n"
+ "    <div class=\"progress-container\">\n"
+ "      <div class=\"progress\">\n"
+ "        <div class=\"progress-bar\" role=\"progressbar\">\n"
+ "          <span id=\"progressText\">Step 1 of 4</span>\n"
+ "        </div>\n"
+ "      </div>\n"
+ "    </div>\n"
+ "\n"
// STEP 1
+ "    <div class=\"form-section active\" id=\"step-1\">\n"
+ "      <h2>Step 1: Basic Information</h2>\n"
+ "      <form id=\"formStep1\">\n"
+ "        <label class=\"form-label\" for=\"firstName\">First Name</label>\n"
+ "        <input type=\"text\" class=\"form-control\" id=\"firstName\" required placeholder=\"Enter your first name\">\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"lastName\">Last Name</label>\n"
+ "        <input type=\"text\" class=\"form-control\" id=\"lastName\" required placeholder=\"Enter your last name\">\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"emailAddress\">Email Address</label>\n"
+ "        <input type=\"email\" class=\"form-control\" id=\"emailAddress\" required placeholder=\"Enter your email address\">\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"phoneNumber\">Phone Number</label>\n"
+ "        <input type=\"tel\" class=\"form-control\" id=\"phoneNumber\" required placeholder=\"Enter your phone number\">\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"gender\">Gender</label>\n"
+ "        <select id=\"gender\" class=\"form-select\" required>\n"
+ "          <option value=\"\">Select Gender</option>\n"
+ "          <option>Male</option>\n"
+ "          <option>Female</option>\n"
+ "          <option>Other</option>\n"
+ "          <option>Prefer Not to Say</option>\n"
+ "        </select>\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"artistSelect\">Select Artist/Label</label>\n"
+ "        <select id=\"artistSelect\" class=\"form-select\" required>\n"
+ "          <option value=\"\">-- Select Artist or Label --</option>\n"
+ "          <option>Aaron Lewis</option>\n"
+ "          <option>Badflower</option>\n"
+ "          <option>Braedon Barnill</option>\n"
+ "          <option>Brantley Gilbert</option>\n"
+ "          <option>Brett Young</option>\n"
+ "          <option>Brian Kelley</option>\n"
+ "          <option>Carly Pearce</option>\n"
+ "          <option>Chase McDaniel</option>\n"
+ "          <option>Chris Janson</option>\n"
+ "          <option>Conner Smith</option>\n"
+ "          <option>Daughtry</option>\n"
+ "          <option>Dolly Parton</option>\n"
+ "          <option>Dylan Matthew</option>\n"
+ "          <option>Eli Young Band</option>\n"
+ "          <option>Florida Georgia Line</option>\n"
+ "          <option>Gary LeVox</option>\n"
+ "          <option>Glen Campbell</option>\n"
+ "          <option>Greylan James</option>\n"
+ "          <option>Jack Wharff</option>\n"
+ "          <option>Jackson Dean</option>\n"
+ "          <option>Justin Moore</option>\n"
+ "          <option>Kidd G</option>\n"
+ "          <option>Kristian Bush</option>\n"
+ "          <option>Lady A</option>\n"
+ "          <option>Lecade</option>\n"
+ "          <option>Lillian Hepler</option>\n"
+ "          <option>Mackenzie Carpenter</option>\n"
+ "          <option>Mae Estes</option>\n"
+ "          <option>Midland</option>\n"
+ "          <option>Mötley Crüe</option>\n"
+ "          <option>Noah Hicks</option>\n"
+ "          <option>Rascal Flatts</option>\n"
+ "          <option>Ray Wylie Hubbard</option>\n"
+ "          <option>Riley Green</option>\n"
+ "          <option>Ryan Hurd</option>\n"
+ "          <option>Ryan Perdz</option>\n"
+ "          <option>Savana Santos</option>\n"
+ "          <option>Shaylen</option>\n"
+ "          <option>Sheryl Crow</option>\n"
+ "          <option>Sugarland</option>\n"
+ "          <option>The Cadillac Three</option>\n"
+ "          <option>The Struts</option>\n"
+ "          <option>Thomas Rhett</option>\n"
+ "          <option>Tim McGraw</option>\n"
+ "        </select>\n"
+ "      </form>\n"
+ "    </div>\n"
+ "\n"
// STEP 2
+ "    <div class=\"form-section\" id=\"step-2\">\n"
+ "      <h2>Step 2: Address Information</h2>\n"
+ "      <form id=\"formStep2\">\n"
+ "        <label class=\"form-label\" for=\"streetAddress\">Street Address</label>\n"
+ "        <input type=\"text\" class=\"form-control\" id=\"streetAddress\" required placeholder=\"Enter your street address\">\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"city\">City</label>\n"
+ "        <input type=\"text\" class=\"form-control\" id=\"city\" required placeholder=\"Enter your city\">\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"state\">State</label>\n"
+ "        <select id=\"state\" class=\"form-select\" required>\n"
+ "          <option value=\"\">Select State</option>\n"
+ "          <option>AL - Alabama</option>\n"
+ "          <option>AK - Alaska</option>\n"
+ "          <option>AZ - Arizona</option>\n"
+ "          <option>AR - Arkansas</option>\n"
+ "          <option>CA - California</option>\n"
+ "          <option>CO - Colorado</option>\n"
+ "          <option>CT - Connecticut</option>\n"
+ "          <option>DE - Delaware</option>\n"
+ "          <option>FL - Florida</option>\n"
+ "          <option>GA - Georgia</option>\n"
+ "          <option>HI - Hawaii</option>\n"
+ "          <option>ID - Idaho</option>\n"
+ "          <option>IL - Illinois</option>\n"
+ "          <option>IN - Indiana</option>\n"
+ "          <option>IA - Iowa</option>\n"
+ "          <option>KS - Kansas</option>\n"
+ "          <option>KY - Kentucky</option>\n"
+ "          <option>LA - Louisiana</option>\n"
+ "          <option>ME - Maine</option>\n"
+ "          <option>MD - Maryland</option>\n"
+ "          <option>MA - Massachusetts</option>\n"
+ "          <option>MI - Michigan</option>\n"
+ "          <option>MN - Minnesota</option>\n"
+ "          <option>MS - Mississippi</option>\n"
+ "          <option>MO - Missouri</option>\n"
+ "          <option>MT - Montana</option>\n"
+ "          <option>NE - Nebraska</option>\n"
+ "          <option>NV - Nevada</option>\n"
+ "          <option>NH - New Hampshire</option>\n"
+ "          <option>NJ - New Jersey</option>\n"
+ "          <option>NM - New Mexico</option>\n"
+ "          <option>NY - New York</option>\n"
+ "          <option>NC - North Carolina</option>\n"
+ "          <option>ND - North Dakota</option>\n"
+ "          <option>OH - Ohio</option>\n"
+ "          <option>OK - Oklahoma</option>\n"
+ "          <option>OR - Oregon</option>\n"
+ "          <option>PA - Pennsylvania</option>\n"
+ "          <option>RI - Rhode Island</option>\n"
+ "          <option>SC - South Carolina</option>\n"
+ "          <option>SD - South Dakota</option>\n"
+ "          <option>TN - Tennessee</option>\n"
+ "          <option>TX - Texas</option>\n"
+ "          <option>UT - Utah</option>\n"
+ "          <option>VT - Vermont</option>\n"
+ "          <option>VA - Virginia</option>\n"
+ "          <option>WA - Washington</option>\n"
+ "          <option>WV - West Virginia</option>\n"
+ "          <option>WI - Wisconsin</option>\n"
+ "          <option>WY - Wyoming</option>\n"
+ "        </select>\n"
+ "\n"
+ "        <label class=\"form-label\" for=\"zipCode\">ZIP Code</label>\n"
+ "        <input type=\"text\" class=\"form-control\" id=\"zipCode\" required placeholder=\"Enter your ZIP code\">\n"
+ "      </form>\n"
+ "    </div>\n"
+ "\n"
// STEP 3
+ "    <div class=\"form-section\" id=\"step-3\">\n"
+ "      <h2>Step 3: Signature Capture</h2>\n"
+ "      <canvas id=\"signatureCanvas\"></canvas>\n"
+ "      <div style=\"margin-top:1rem;\">\n"
+ "        <button class=\"btn btn-previous\" type=\"button\" id=\"clearSignature\">Clear Signature</button>\n"
+ "        <button class=\"btn btn-info\" type=\"button\" id=\"downloadSignatureBtn\">Download Signature</button>\n"
+ "      </div>\n"
+ "    </div>\n"
+ "\n"
// STEP 4
+ "    <div class=\"form-section\" id=\"step-4\">\n"
+ "      <h2>Step 4: Face Capture</h2>\n"
+ "      <button class=\"btn btn-camera\" type=\"button\" id=\"enableCamera\">Enable Camera</button>\n"
+ "      <video id=\"videoElement\" autoplay playsinline></video>\n"
+ "      <img id=\"capturedImage\" alt=\"Captured Photo\">\n"
+ "      <div style=\"margin-top:1rem;\">\n"
+ "        <button class=\"btn btn-camera\" type=\"button\" id=\"capturePhoto\">Capture Photo</button>\n"
+ "        <button class=\"btn btn-previous\" type=\"button\" id=\"retakePhoto\">Retake Photo</button>\n"
+ "        <button class=\"btn btn-info\" type=\"button\" id=\"downloadPhotoBtn\">Download Photo</button>\n"
+ "      </div>\n"
+ "    </div>\n"
+ "\n"
// NAV BUTTONS
+ "    <div class=\"navigation-buttons\">\n"
+ "      <button class=\"btn btn-previous\" id=\"prevBtn\" disabled>Previous</button>\n"
+ "      <button class=\"btn btn-next\" id=\"nextBtn\">Next</button>\n"
+ "    </div>\n"
+ "\n"
+ "    <div class=\"spinner\" id=\"spinner\">\n"
+ "      <p>Generating PDF, please wait...</p>\n"
+ "    </div>\n"
+ "    <div class=\"final-instructions\" id=\"finalInstructions\">\n"
+ "      Download your filled form and send it to <strong>pr@bmlgartists.com</strong>.<br>\n"
+ "      Your application will be responded to within 24 hours maximum.\n"
+ "    </div>\n"
+ "  </div>\n"
+ "\n"
// Inline JS
+ "  <script>\n"
+ "    var jsPDF = window.jspdf.jsPDF;\n"
+ "    var currentStep = 1;\n"
+ "    var totalSteps = 4;\n"
+ "    var stepForms = [\n"
+ "      document.getElementById('step-1'),\n"
+ "      document.getElementById('step-2'),\n"
+ "      document.getElementById('step-3'),\n"
+ "      document.getElementById('step-4')\n"
+ "    ];\n"
+ "\n"
+ "    var prevBtn = document.getElementById('prevBtn');\n"
+ "    var nextBtn = document.getElementById('nextBtn');\n"
+ "    var progressBar = document.querySelector('.progress-bar');\n"
+ "    var progressText = document.getElementById('progressText');\n"
+ "    var spinner = document.getElementById('spinner');\n"
+ "    var finalInstructions = document.getElementById('finalInstructions');\n"
+ "\n"
+ "    // SIGNATURE\n"
+ "    var canvas = document.getElementById('signatureCanvas');\n"
+ "    var ctx = canvas.getContext('2d');\n"
+ "    var isDrawing=false;\n"
+ "    var lastX=0;\n"
+ "    var lastY=0;\n"
+ "    var signatureDrawn=false;\n"
+ "\n"
+ "    // CAMERA\n"
+ "    var videoStream=null;\n"
+ "    var capturedImageData=null;\n"
+ "    var videoElement=document.getElementById('videoElement');\n"
+ "    var capturedImage=document.getElementById('capturedImage');\n"
+ "\n"
+ "    // Buttons\n"
+ "    var clearSignatureBtn=document.getElementById('clearSignature');\n"
+ "    var downloadSignatureBtn=document.getElementById('downloadSignatureBtn');\n"
+ "    var downloadPhotoBtn=document.getElementById('downloadPhotoBtn');\n"
+ "    var enableCameraBtn=document.getElementById('enableCamera');\n"
+ "    var capturePhotoBtn=document.getElementById('capturePhoto');\n"
+ "    var retakePhotoBtn=document.getElementById('retakePhoto');\n"
+ "\n"
+ "    document.addEventListener('DOMContentLoaded', function(){\n"
+ "      // Canvas config\n"
+ "      ctx.strokeStyle='#000';\n"
+ "      ctx.lineWidth=2.5;\n"
+ "      ctx.lineCap='round';\n"
+ "\n"
+ "      // Canvas events\n"
+ "      canvas.addEventListener('pointerdown', pointerDown);\n"
+ "      canvas.addEventListener('pointermove', pointerMove);\n"
+ "      canvas.addEventListener('pointerup', function(){isDrawing=false;});\n"
+ "      canvas.addEventListener('pointercancel', function(){isDrawing=false;});\n"
+ "      canvas.addEventListener('pointerout', function(){isDrawing=false;});\n"
+ "\n"
+ "      clearSignatureBtn.addEventListener('click', clearSignature);\n"
+ "      downloadSignatureBtn.addEventListener('click', downloadSignature);\n"
+ "\n"
+ "      enableCameraBtn.addEventListener('click', enableCamera);\n"
+ "      capturePhotoBtn.addEventListener('click', capturePhoto);\n"
+ "      retakePhotoBtn.addEventListener('click', retakePhoto);\n"
+ "      downloadPhotoBtn.addEventListener('click', downloadPhoto);\n"
+ "\n"
+ "      nextBtn.addEventListener('click', handleNext);\n"
+ "      prevBtn.addEventListener('click', handlePrev);\n"
+ "\n"
+ "      showStep(currentStep);\n"
+ "    });\n"
+ "\n"
+ "    function pointerDown(e){\n"
+ "      isDrawing=true;\n"
+ "      var coords=getCanvasCoords(e);\n"
+ "      lastX=coords.x; lastY=coords.y;\n"
+ "    }\n"
+ "    function pointerMove(e){\n"
+ "      if(!isDrawing)return;\n"
+ "      var coords=getCanvasCoords(e);\n"
+ "      ctx.beginPath();\n"
+ "      ctx.moveTo(lastX,lastY);\n"
+ "      ctx.lineTo(coords.x,coords.y);\n"
+ "      ctx.stroke();\n"
+ "      lastX=coords.x; lastY=coords.y;\n"
+ "      signatureDrawn=true;\n"
+ "    }\n"
+ "    function getCanvasCoords(e){\n"
+ "      var rect=canvas.getBoundingClientRect();\n"
+ "      var scaleX=canvas.width/rect.width;\n"
+ "      var scaleY=canvas.height/rect.height;\n"
+ "      return {\n"
+ "        x:(e.clientX-rect.left)*scaleX,\n"
+ "        y:(e.clientY-rect.top)*scaleY\n"
+ "      };\n"
+ "    }\n"
+ "    function clearSignature(){\n"
+ "      ctx.clearRect(0,0,canvas.width,canvas.height);\n"
+ "      signatureDrawn=false;\n"
+ "    }\n"
+ "    function downloadSignature(){\n"
+ "      if(!signatureDrawn){\n"
+ "        alert('No signature to download.');\n"
+ "        return;\n"
+ "      }\n"
+ "      var dataURL=canvas.toDataURL('image/png');\n"
+ "      var link=document.createElement('a');\n"
+ "      link.href=dataURL;\n"
+ "      link.download='Signature.png';\n"
+ "      link.click();\n"
+ "    }\n"
+ "\n"
+ "    function enableCamera(){\n"
+ "      if(navigator.mediaDevices && navigator.mediaDevices.getUserMedia){\n"
+ "        navigator.mediaDevices.getUserMedia({video:true}).then(function(stream){\n"
+ "          videoStream=stream;\n"
+ "          videoElement.srcObject=stream;\n"
+ "          videoElement.style.display='block';\n"
+ "          capturedImage.style.display='none';\n"
+ "        }).catch(function(err){\n"
+ "          alert('Error: Unable to access camera.');\n"
+ "        });\n"
+ "      } else {\n"
+ "        alert('Error: Browser does not support camera.');\n"
+ "      }\n"
+ "    }\n"
+ "    function capturePhoto(){\n"
+ "      if(!videoStream){\n"
+ "        alert('Error: Camera not enabled.');\n"
+ "        return;\n"
+ "      }\n"
+ "      var tempCanvas=document.createElement('canvas');\n"
+ "      tempCanvas.width=videoElement.videoWidth;\n"
+ "      tempCanvas.height=videoElement.videoHeight;\n"
+ "      var tempCtx=tempCanvas.getContext('2d');\n"
+ "      tempCtx.drawImage(videoElement,0,0,tempCanvas.width,tempCanvas.height);\n"
+ "      capturedImageData=tempCanvas.toDataURL('image/png');\n"
+ "      capturedImage.src=capturedImageData;\n"
+ "      capturedImage.style.display='block';\n"
+ "      videoElement.style.display='none';\n"
+ "    }\n"
+ "    function retakePhoto(){\n"
+ "      if(videoStream){\n"
+ "        videoElement.style.display='block';\n"
+ "      }\n"
+ "      capturedImage.style.display='none';\n"
+ "      capturedImageData=null;\n"
+ "    }\n"
+ "    function downloadPhoto(){\n"
+ "      if(!capturedImageData){\n"
+ "        alert('No photo to download.');\n"
+ "        return;\n"
+ "      }\n"
+ "      var link=document.createElement('a');\n"
+ "      link.href=capturedImageData;\n"
+ "      link.download='CapturedPhoto.png';\n"
+ "      link.click();\n"
+ "    }\n"
+ "\n"
+ "    function handleNext(){\n"
+ "      if(currentStep<totalSteps){\n"
+ "        currentStep++;\n"
+ "        showStep(currentStep);\n"
+ "      } else {\n"
+ "        // Final => Validate + Generate PDF\n"
+ "        if(!validateAllSteps())return;\n"
+ "        generatePdfDownload();\n"
+ "      }\n"
+ "    }\n"
+ "    function handlePrev(){\n"
+ "      if(currentStep>1){\n"
+ "        currentStep--;\n"
+ "        showStep(currentStep);\n"
+ "      }\n"
+ "    }\n"
+ "    function showStep(step){\n"
+ "      for(var i=0;i<stepForms.length;i++){\n"
+ "        stepForms[i].classList.remove('active');\n"
+ "      }\n"
+ "      stepForms[step-1].classList.add('active');\n"
+ "      prevBtn.disabled=(step===1);\n"
+ "      var progress=(step/totalSteps)*100;\n"
+ "      progressBar.style.width=progress+'%';\n"
+ "      progressText.textContent='Step '+step+' of '+totalSteps;\n"
+ "      nextBtn.textContent=(step===totalSteps)?'Download Filled Form':'Next';\n"
+ "    }\n"
+ "    function validateAllSteps(){\n"
+ "      if(!signatureDrawn){\n"
+ "        alert('Please provide a signature (Step 3) before downloading.');\n"
+ "        return false;\n"
+ "      }\n"
+ "      return true;\n"
+ "    }\n"
+ "    function generatePdfDownload(){\n"
+ "      spinner.style.display='block';\n"
+ "\n"
+ "      var firstName=document.getElementById('firstName').value.trim();\n"
+ "      var lastName=document.getElementById('lastName').value.trim();\n"
+ "      var emailAddress=document.getElementById('emailAddress').value.trim();\n"
+ "      var phoneNumber=document.getElementById('phoneNumber').value.trim();\n"
+ "      var gender=document.getElementById('gender').value;\n"
+ "      var artist=document.getElementById('artistSelect').value;\n"
+ "\n"
+ "      var streetAddress=document.getElementById('streetAddress').value.trim();\n"
+ "      var city=document.getElementById('city').value.trim();\n"
+ "      var state=document.getElementById('state').value;\n"
+ "      var zipCode=document.getElementById('zipCode').value.trim();\n"
+ "\n"
+ "      var signatureBase64=canvas.toDataURL('image/png');\n"
+ "      var photoBase64=capturedImageData;\n"
+ "\n"
+ "      var doc=new jsPDF({ unit:'pt', format:'letter' });\n"
+ "      doc.setFontSize(16);\n"
+ "      doc.text('Meet With Artist Application', 40,50);\n"
+ "\n"
+ "      doc.setFontSize(12);\n"
+ "      var yPos=80;\n"
+ "      doc.text('Name: '+ firstName+' '+lastName, 40,yPos); yPos+=20;\n"
+ "      doc.text('Email: '+ emailAddress, 40,yPos); yPos+=20;\n"
+ "      doc.text('Phone: '+ phoneNumber, 40,yPos); yPos+=20;\n"
+ "      doc.text('Gender: '+ gender, 40,yPos); yPos+=20;\n"
+ "      doc.text('Artist: '+ artist, 40,yPos); yPos+=30;\n"
+ "\n"
+ "      doc.text('Street: '+ streetAddress, 40,yPos); yPos+=20;\n"
+ "      doc.text('City: '+ city, 40,yPos); yPos+=20;\n"
+ "      doc.text('State: '+ state, 40,yPos); yPos+=20;\n"
+ "      doc.text('ZIP: '+ zipCode, 40,yPos); yPos+=30;\n"
+ "\n"
+ "      if(signatureBase64){\n"
+ "        doc.text('Signature:', 40,yPos); yPos+=10;\n"
+ "        doc.addImage(signatureBase64, 'PNG', 40,yPos,150,50);\n"
+ "        yPos+=70;\n"
+ "      }\n"
+ "      if(photoBase64){\n"
+ "        doc.text('Captured Photo:', 40,yPos); yPos+=10;\n"
+ "        doc.addImage(photoBase64, 'PNG', 40,yPos,150,100);\n"
+ "        yPos+=120;\n"
+ "      }\n"
+ "\n"
+ "      doc.save('MeetWithArtistApplication.pdf');\n"
+ "      spinner.style.display='none';\n"
+ "      finalInstructions.style.display='block';\n"
+ "      alert('PDF downloaded successfully! Please email it to pr@bmlgartists.com.');\n"
+ "    }\n"
+ "  </script>\n"
+ "</body>\n"
+ "</html>\n";

  res.send(htmlContent);
});

// Start the server
app.listen(PORT, function() {
  console.log("Server running at http://localhost:" + PORT);
});
